pool: Default 

trigger: none

pr:
    - develop

variables:
  webproject: 'src/Presentation/Nop.Web/Nop.Web.csproj'
  testproject: 'src/Tests/Nop.Tests/Nop.Tests.csproj'

steps: 
     - task: JFrogNuGet@1
       inputs:
        command: 'restore'
        artifactoryConnection: 'Jfrog_cloud'
        targetResolveRepo: 'classroomhw-libs-release'
        solutionPath: '**/*.sln'
     - template: 'template/nopcommarce-build.yaml'
   

