pool: Default 

trigger: none

pr:
    - develop

variables:
  webproject: 'src/Presentation/Nop.Web/Nop.Web.csproj'
  testproject: 'src/Tests/Nop.Tests/Nop.Tests.csproj'

steps:
   - task: DotNetCoreCLI@2
     inputs:
      command: 'build'

   - task: JFrogDotnetCore@1
     inputs:
      command: 'restore'
      artifactoryConnection: 'Jfrog_cloud'
      rootPath: '**/*.sln'

   - template: 'template/nopcommarce-build.yaml'
   

