pool: Default 


trigger: none

pr:
    - develop

variables:
  webproject: 'src/Presentation/Nop.Web/Nop.Web.csproj'
  testproject: 'src/Tests/Nop.Tests/Nop.Tests.csproj'

steps: 
     - task: JFrogPublishBuildInfo@1
       inputs:
         artifactoryConnection: 'Jfrog_dotnet_project'
         buildName: '$(Build.DefinitionName)'
         buildNumber: '$(Build.BuildNumber)'
         projectKey: 'nopcommarce123'
         
     - task: JFrogGenericArtifacts@1
       inputs:
         command: 'Upload'
         connection: 'Jfrog_dotnet_project'
         specSource: 'taskConfiguration'
         fileSpec: |
           {
             "files": [
               {
                 "pattern": ".war",
                 "target": "artifactory-build-info"
               }
             ]
           }
         failNoOp: true
     - template: 'template/nopcommarce-build.yaml'
   

