pool: Default 

trigger: none

pr:
    - develop

variables:
  webproject: 'src/Presentation/Nop.Web/Nop.Web.csproj'
  testproject: 'src/Tests/Nop.Tests/Nop.Tests.csproj'


steps:
- template: 'template/nopcommarce-build.yaml'
